# Generated by Django 5.0.14 on 2026-07-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_caja_sesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDesdeCotizacion',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido desde cotización',
                'verbose_name_plural': 'Pedidos desde cotización',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pedidos.pedido',),
        ),
        migrations.CreateModel(
            name='PedidoWeb',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido web',
                'verbose_name_plural': 'Pedidos web',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pedidos.pedido',),
        ),
        migrations.CreateModel(
            name='VentaTienda',
            fields=[
            ],
            options={
                'verbose_name': 'Venta de tienda',
                'verbose_name_plural': 'Ventas de tienda',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pedidos.pedido',),
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_pedido'], 'verbose_name': 'Pedido / Venta', 'verbose_name_plural': 'Pedidos y ventas'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('enviado', 'Listo para recojo'), ('entregado', 'Entregado / Retirado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado de Pedido'),
        ),
    ]
