# Generated by Django 5.0.14 on 2026-07-21 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_proxy_ventas_web_tienda'),
        ('sistema', '0002_sedes_reserva_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='reservado_hasta',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='sistema.sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stock_reservado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='voucher',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/%Y/%m/'),
        ),
    ]
