# Generated by Django 5.0.14 on 2026-06-05 04:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_etiqueta'),
        ('tienda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número de Cotización')),
                ('nombre_cliente_temporal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Cliente (Manual)')),
                ('dni_ruc_cliente_temporal', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI/RUC (Manual)')),
                ('correo_cliente_temporal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo (Manual)')),
                ('telefono_cliente_temporal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono (Manual)')),
                ('modelo_equipo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo de Equipo (ej. HP2070)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada al Cliente'), ('aprobada', 'Aprobada (Convertida)'), ('rechazada', 'Rechazada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IGV (18%)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas / Observaciones')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='clientes.cliente', verbose_name='Cliente CRM')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_manual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción Manual (si no está en catálogo)')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizaciones.cotizacion', verbose_name='Cotización')),
                ('repuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_cotizados', to='tienda.producto', verbose_name='Repuesto Catálogo')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
            },
        ),
    ]
