# Generated by Django 5.0.14 on 2026-08-08 03:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_cotizacion_estado_anulada'),
        ('tienda', '0011_alter_importacioncatalogo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='modelo_equipo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo de Equipo'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='descripcion_manual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción Manual (legacy)'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_cotizados', to='tienda.producto', verbose_name='Producto catálogo'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor / subtotal'),
        ),
    ]
