# Generated by Django 5.0.14 on 2026-08-10 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_cotizacion_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='token_publico',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de acceso público'),
        ),
    ]
