# Generated by Django 5.0.14 on 2026-06-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo o Razón Social')),
                ('tipo', models.CharField(choices=[('persona', 'Persona Natural'), ('empresa', 'Empresa / Jurídica')], default='persona', max_length=20, verbose_name='Tipo de Cliente')),
                ('dni_ruc', models.CharField(max_length=20, unique=True, verbose_name='DNI o RUC')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(default='Arequipa', max_length=100, verbose_name='Ciudad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('canal_origen', models.CharField(choices=[('web', 'Tienda Web'), ('pos', 'Tienda Física / POS'), ('referido', 'Referido / Otro')], default='web', max_length=20, verbose_name='Canal de Origen')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
            ],
            options={
                'verbose_name': 'Cliente (CRM)',
                'verbose_name_plural': 'Clientes (CRM)',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
