# Generated by Django 5.0.14 on 2026-06-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='etiqueta',
            field=models.CharField(choices=[('nuevo', 'Cliente Nuevo'), ('frecuente', 'Cliente Frecuente'), ('vip', 'Cliente VIP'), ('empresa', 'Empresa'), ('inactivo', 'Cliente Inactivo')], default='nuevo', max_length=20, verbose_name='Clasificación / Etiqueta'),
        ),
    ]
