from django.urls import path
from . import views
from . import views_hub
from . import views_historial

app_name = 'pos'

urlpatterns = [
    path('pos/login/', views.PosLoginView.as_view(), name='login'),
    path('pos/', views.pos_dashboard, name='dashboard'),
    path('pos/inicio/', views_hub.hub_inicio, name='hub_inicio'),
    path('pos/ventas/', views_hub.hub_ventas_tienda, name='hub_ventas'),
    path('pos/ventas/<int:pedido_id>/', views_hub.hub_pedido_detalle, name='hub_pedido_detalle'),
    path('pos/pedidos-web/', views_hub.hub_pedidos_web, name='hub_pedidos_web'),
    path('pos/productos/buscar/', views.buscar_productos, name='buscar_productos'),
    path('pos/productos/', views_hub.hub_productos, name='hub_productos'),
    path('pos/productos/nuevo/', views_hub.hub_producto_nuevo, name='hub_producto_nuevo'),
    path('pos/productos-web/', views_hub.hub_productos_web, name='hub_productos_web'),
    path('pos/productos-web/buscar-catalogo/', views_hub.hub_productos_web_buscar, name='hub_productos_web_buscar'),
    path('pos/productos-web/bulk/', views_hub.hub_productos_web_bulk, name='hub_productos_web_bulk'),
    path('pos/productos-web/<int:producto_id>/toggle/', views_hub.hub_producto_web_toggle, name='hub_producto_web_toggle'),
    path('pos/productos/<int:producto_id>/editar/', views_hub.hub_producto_editar, name='hub_producto_editar'),
    path('pos/inventario/', views_hub.hub_inventario, name='hub_inventario'),
    path('pos/inventario/buscar/', views_hub.hub_inventario_buscar, name='hub_inventario_buscar'),
    path('pos/inventario/aplicar/', views_hub.hub_inventario_aplicar, name='hub_inventario_aplicar'),
    path('pos/inventario/ingreso-rapido/', views_hub.hub_inventario_ingreso_rapido, name='hub_inventario_ingreso_rapido'),
    path('pos/actividad/', views_hub.hub_actividad, name='hub_actividad'),
    path('pos/clientes/', views_hub.hub_clientes, name='hub_clientes'),
    path('pos/pagos/', views_hub.hub_pagos, name='hub_pagos'),
    path('pos/movimientos/', views_hub.hub_movimientos, name='hub_movimientos'),
    path('pos/importar/', views_hub.hub_importar, name='hub_importar'),
    path('pos/importar/upload/', views_hub.hub_importar_upload, name='hub_importar_upload'),
    path('pos/importar/<int:importacion_id>/estado/', views_hub.hub_importar_estado, name='hub_importar_estado'),
    path('pos/importar/<int:importacion_id>/detalle/', views_hub.hub_importar_detalle, name='hub_importar_detalle'),
    path('pos/importar/<int:importacion_id>/cancelar/', views_hub.hub_importar_cancelar, name='hub_importar_cancelar'),
    path('pos/importar/<int:importacion_id>/reanudar/', views_hub.hub_importar_reanudar, name='hub_importar_reanudar'),
    path('pos/caja/movimiento/', views_hub.hub_caja_movimiento, name='hub_caja_movimiento'),
    path('pos/consulta-documento/', views_hub.hub_consulta_documento, name='hub_consulta_documento'),
    path('pos/salir/', views_hub.hub_salir, name='hub_salir'),
    path('pos/salir/confirmar/', views_hub.hub_salir_confirmar, name='hub_salir_confirmar'),
    path('pos/respaldo/', views_hub.hub_respaldo, name='hub_respaldo'),
    path('pos/respaldo/exportar/', views_hub.hub_respaldo_exportar, name='hub_respaldo_exportar'),
    path('pos/respaldo/importar/', views_hub.hub_respaldo_importar, name='hub_respaldo_importar'),
    path('pos/respaldo/reiniciar-operativo/', views_hub.hub_reiniciar_operativo, name='hub_reiniciar_operativo'),
    path('pos/respaldo/correlativo-ot/', views_hub.hub_configurar_ot_correlativo, name='hub_configurar_ot_correlativo'),
    path('pos/historial-precios/', views_historial.hub_historial_precios, name='hub_historial_precios'),
    path('pos/historial-precios/buscar/', views_historial.hub_historial_precios_buscar, name='hub_historial_precios_buscar'),
    path('pos/historial-precios/<int:producto_id>/datos/', views_historial.hub_historial_precios_datos, name='hub_historial_precios_datos'),
    path('pos/abrir/', views.abrir_caja, name='abrir_caja'),
    path('pos/cerrar/<int:sesion_id>/', views.cerrar_caja, name='cerrar_caja'),
    path('pos/venta/registrar/', views.registrar_venta, name='registrar_venta'),
    path('pos/ticket/<int:ticket_id>/imprimir/', views.imprimir_ticket, name='imprimir_ticket'),
    path('pos/cierre/<int:sesion_id>/exportar/', views.exportar_cierre_caja, name='exportar_cierre_caja'),
]
