# Generated by Django 5.0.14 on 2026-06-04 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Ingreso)'), ('salida', 'Salida (Egreso)')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('motivo', models.CharField(choices=[('compra', 'Compra / Abastecimiento'), ('venta_web', 'Venta Web'), ('venta_pos', 'Venta POS / Tienda'), ('ajuste', 'Ajuste de Inventario'), ('mantenimiento', 'Repuestos Mantenimiento')], default='ajuste', max_length=20, verbose_name='Motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tienda.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
