# Generated by Django 5.0.14 on 2026-07-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientoinventario_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(choices=[('compra', 'Compra / Abastecimiento'), ('venta_web', 'Venta Web'), ('venta_pos', 'Venta POS / Tienda'), ('ajuste', 'Ajuste de Inventario'), ('mantenimiento', 'Repuestos Mantenimiento'), ('reserva_web', 'Reserva pedido web'), ('liberacion_web', 'Liberación reserva web'), ('transferencia', 'Transferencia tienda ↔ web')], default='ajuste', max_length=20, verbose_name='Motivo'),
        ),
    ]
