# Generated by Django 5.0.14 on 2026-08-11 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0013_alter_producto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespieceEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(db_index=True, help_text='Ej: GA4590, DHP484, HR2470', max_length=50, unique=True, verbose_name='Modelo del Equipo')),
                ('nombre_equipo', models.CharField(help_text='Ej: Esmeriladora Angular 115mm', max_length=255, verbose_name='Descripción / Nombre del Equipo')),
                ('archivo_pdf', models.CharField(blank=True, default='', max_length=255, verbose_name='Ruta del PDF de Origen')),
                ('imagen_diagrama', models.ImageField(blank=True, null=True, upload_to='despieces/diagramas/', verbose_name='Imagen Renderizada del Diagrama Explosionado')),
                ('total_partes', models.PositiveIntegerField(default=0, verbose_name='Total de Partes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Despiece de Equipo',
                'verbose_name_plural': 'Despieces de Equipos',
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='DespieceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(db_index=True, help_text='Ej: 016, 017, 068-1', max_length=30, verbose_name='Posición en Diagrama (Art. No.)')),
                ('codigo_articulo', models.CharField(db_index=True, help_text='Ej: 511A48-8, 681656-4', max_length=50, verbose_name='Número de Parte / SKU')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Repuesto / Parte')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad requerida por equipo')),
                ('despiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='despiece.despieceequipo', verbose_name='Despiece de Equipo')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despieces_asociados', to='tienda.producto', verbose_name='Producto en Catálogo Sistema')),
            ],
            options={
                'verbose_name': 'Ítem de Despiece',
                'verbose_name_plural': 'Ítems de Despieces',
                'ordering': ['id'],
            },
        ),
    ]
