# Generated by Django 5.0.14 on 2026-06-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta Crédito/Débito'), ('transferencia', 'Transferencia Bancaria')], default='tarjeta', max_length=20, verbose_name='Método de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Confirmación'), ('aprobado', 'Aprobado / Pagado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado del Pago')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia Pasarela (ID Transacción)')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
