# Generated by Django 5.0.14 on 2026-07-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('tienda', 'Pagar en tienda')], default='tarjeta', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
