# Generated by Django 5.0.14 on 2026-07-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_sedes_reserva_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='voucher',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/pagos/%Y/%m/', verbose_name='Voucher / captura de pago'),
        ),
    ]
