# Generated by Django 5.0.14 on 2026-07-21 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_log_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='STA El Charly Makita', max_length=150)),
                ('nombre_corto', models.CharField(default='El Charly', max_length=80)),
                ('ruc', models.CharField(blank=True, default='', max_length=11)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('tienda', 'Tienda'), ('taller', 'Taller'), ('otro', 'Otro')], default='tienda', max_length=20)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('whatsapp', models.CharField(blank=True, default='', help_text='Solo dígitos con código país, ej. 51960160842', max_length=20)),
                ('yape_numero', models.CharField(blank=True, default='', max_length=20)),
                ('yape_titular', models.CharField(blank=True, default='', max_length=120)),
                ('yape_qr', models.ImageField(blank=True, null=True, upload_to='sedes/yape/')),
                ('compartir_productos', models.BooleanField(default=True, help_text='Desactiva para que esta sede maneje stock propio.', verbose_name='Compartir productos/stock con otras sedes')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='sistema.empresa')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
