# Generated by Django 5.0.14 on 2026-07-21 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_sedes_reserva_validacion'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sede_activa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_activos', to='sistema.sede', verbose_name='Sede activa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sedes',
            field=models.ManyToManyField(blank=True, help_text='Una o ambas sedes (tienda / taller).', related_name='usuarios', to='sistema.sede', verbose_name='Sedes asignadas'),
        ),
    ]
