"""
Django settings for proyecto_makita project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(
    DEBUG=(bool, False),
    WEB_PUBLICA_ACTIVA=(bool, False),  # False = tienda online “en construcción”
)
# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# Tienda online pública (/ catalogo, carrito, etc.). El sistema interno (POS) no depende de esto.
WEB_PUBLICA_ACTIVA = env('WEB_PUBLICA_ACTIVA')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'unfold',  # must be before django.contrib.admin
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Local apps
    'apps.usuarios',
    'apps.tienda',
    'apps.pedidos',
    'apps.clientes',
    'apps.mantenimiento',
    'apps.cotizaciones',
    'apps.inventario',
    'apps.pagos',
    'apps.pos',
    'apps.reportes',
    'apps.despiece',
    'apps.sistema.apps.SistemaConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.sistema.middleware.TiendaEnConstruccionMiddleware',
    'apps.sistema.middleware.NoIndexInternalMiddleware',
    'apps.sistema.middleware.BrandedErrorPagesMiddleware',
    'apps.sistema.middleware.ActivityLogMiddleware',
]

ROOT_URLCONF = 'proyecto_makita.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.tienda.context_processors.cart',
                'apps.tienda.context_processors.negocio',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_makita.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': env.db()
}
# Reutiliza conexiones Postgres (cortes cortos / failover 4G no abren pool nuevo cada request).
DATABASES['default'].setdefault('CONN_MAX_AGE', env.int('CONN_MAX_AGE', default=60))
DATABASES['default'].setdefault('CONN_HEALTH_CHECKS', True)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Custom user model
AUTH_USER_MODEL = 'usuarios.Usuario'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "El Charly · Admin",
    "SITE_HEADER": "El Charly",
    "SITE_SUBHEADER": "Servicio Técnico Autorizado Makita — Arequipa",
    "COLORS": {
        "primary": {
            "50": "236 253 245",
            "100": "209 250 229",
            "200": "167 243 208",
            "300": "110 231 183",
            "400": "52 211 153",
            "500": "16 185 129",
            "600": "5 150 105",
            "700": "4 120 87",
            "800": "6 95 70",
            "900": "4 78 56",
            "950": "2 48 35",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Inicio"),
                "separator": True,
                "items": [
                    {
                        "title": _("Operaciones (POS)"),
                        "icon": "point_of_sale",
                        "link": reverse_lazy("pos:hub_inicio"),
                    },
                    {
                        "title": _("Admin avanzado"),
                        "icon": "dashboard",
                        "link": "/admin/?stay=1",
                    },
                    {
                        "title": _("Ver tienda web"),
                        "icon": "storefront",
                        "link": reverse_lazy("tienda:home"),
                    },
                ],
            },
            {
                "title": _("Sistema (solo admin)"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Usuarios"),
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:usuarios_usuario_changelist"),
                        "permission": lambda request: request.user.is_superuser or getattr(request.user, 'rol', None) == 'admin',
                    },
                    {
                        "title": _("Exportar / Importar BD"),
                        "icon": "database",
                        "link": reverse_lazy("pos:hub_respaldo"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Sesiones de caja"),
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:pos_cajasesion_changelist"),
                    },
                    {
                        "title": _("Tickets POS"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:pos_ticketpos_changelist"),
                    },
                    {
                        "title": _("Categorías"),
                        "icon": "category",
                        "link": reverse_lazy("admin:tienda_categoria_changelist"),
                    },
                    {
                        "title": _("Logs importación"),
                        "icon": "history",
                        "link": reverse_lazy("admin:tienda_importacioncatalogo_changelist"),
                    },
                ],
            },
            {
                "title": _("Atajos al hub"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Caja / vender"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("pos:dashboard"),
                    },
                    {
                        "title": _("Importar Excel"),
                        "icon": "upload_file",
                        "link": reverse_lazy("pos:hub_importar"),
                    },
                    {
                        "title": _("Productos web"),
                        "icon": "storefront",
                        "link": reverse_lazy("pos:hub_productos_web"),
                    },
                    {
                        "title": _("Productos"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("pos:hub_productos"),
                    },
                    {
                        "title": _("Clientes"),
                        "icon": "groups",
                        "link": reverse_lazy("pos:hub_clientes"),
                    },
                    {
                        "title": _("Reportes"),
                        "icon": "analytics",
                        "link": reverse_lazy("reportes:dashboard"),
                    },
                ],
            },
        ],
    },
}

# Configuración del Carrito de Compras
CART_SESSION_ID = 'cart'

# Datos del negocio — STA El Charly Makita (Arequipa)
NEGOCIO = {
    'nombre': 'STA El Charly Makita',
    'nombre_corto': 'El Charly',
    'ruc': '10431549001',
    'tagline': 'Tu solución Makita en Arequipa',
    'slogan': (
        '¡Tu solución MAKITA en Arequipa! Vendemos herramientas nuevas, '
        'reparamos las tuyas y tenemos todos los repuestos y accesorios. '
        '¡Visítanos y comprueba por qué somos los expertos en MAKITA!'
    ),
    'ciudad': 'Arequipa, Perú',
    'telefono': '(054) 432315',
    'whatsapp': '51960160842',
    'whatsapp_display': '960 160 842',
    'whatsapp_alt': '51935829261',
    'whatsapp_alt_display': '935 829 261',
    'email': 'contacto@elcharlymakita.pe',
    'instagram': 'https://www.instagram.com/makitaelcharly/',
    'facebook': 'https://www.facebook.com/p/Makita-Arequipa-El-Charly-100064003056550/?locale=es_LA',
    'horario_tienda': 'Lun–Sáb 9:00–13:00 y 15:00–19:00',
    'horario_taller': 'Lun–Sáb 9:00–13:00 y 15:00–19:00',
    'horario': 'Lun–Sáb 9:00–13:00 y 15:00–19:00',
    'entrega_activa': False,
    'yape_numero': '960160842',
    'yape_titular': 'STA El Charly Makita',
    # Sube la imagen a media/yape-qr.png o déjalo vacío (se muestra el número)
    'yape_qr_url': '/media/yape-qr.png',
    'pedido_reserva_horas': 24,
    'locales': [
        {
            'tipo': 'taller',
            'titulo': 'Servicio técnico',
            'nombre': 'Galería Divino Jesús',
            'direccion': 'Psj. Santa Catalina N° 100, Int. 6 — Óvalo Mariscal Castilla, Paucarpata',
            'horario': 'Lun–Sáb 9:00–13:00 y 15:00–19:00',
            'mapa_q': 'Galería Divino Jesús Pasaje Santa Catalina 100 Paucarpata Arequipa',
        },
        {
            'tipo': 'tienda',
            'titulo': 'Tienda',
            'nombre': 'Galería ASPYME',
            'direccion': '2do piso — Óvalo de Mariscal Castilla, Paucarpata',
            'horario': 'Lun–Sáb 9:00–13:00 y 15:00–19:00',
            'mapa_q': 'Galería ASPYME Óvalo Mariscal Castilla Paucarpata Arequipa',
        },
    ],
    # Recojo de compras web: tienda ASPYME
    'direccion': 'Galería ASPYME, 2do piso (Óvalo Mariscal Castilla, Paucarpata), Arequipa',
    'mapa_url': 'https://maps.app.goo.gl/pQoEWw5SpkSnDEQU9',
}

# Login / logout
LOGIN_URL = 'usuarios:login'
LOGIN_REDIRECT_URL = '/pos/inicio/'
LOGOUT_REDIRECT_URL = 'usuarios:login'

# Correo (consola en desarrollo; SMTP en producción)
EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = env('EMAIL_HOST', default='localhost')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@elcharlymakita.pe')

# Culqi deshabilitado por ahora (pagos web: Yape/Plin o tienda)

# Consulta DNI/RUC (decolecta | apis_net). Sin token = solo CRM local + llenado manual.
CONSULTA_DOCUMENTO_TOKEN = env('CONSULTA_DOCUMENTO_TOKEN', default='')
CONSULTA_DOCUMENTO_PROVIDER = env('CONSULTA_DOCUMENTO_PROVIDER', default='decolecta')

# Subidas grandes (PDF despiece Makita / Excel)
DATA_UPLOAD_MAX_MEMORY_SIZE = env.int('DATA_UPLOAD_MAX_MEMORY_SIZE', default=52_428_800)  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = env.int('FILE_UPLOAD_MAX_MEMORY_SIZE', default=26_214_400)  # 25 MB

# SLA taller: días máximos en estado ingresado/en proceso sin alerta
MANTENIMIENTO_SLA_DIAS = env.int('MANTENIMIENTO_SLA_DIAS', default=5)
# Datos STA para formulario de garantía Makita (pueden diferir del RUC comercial)
STA_RUC_TECNICO = env('STA_RUC_TECNICO', default='10295867782')
STA_NOMBRE_TECNICO = env('STA_NOMBRE_TECNICO', default='QUISPE PARI FREDY')

# WhiteNoise (archivos estáticos en producción)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Producción detrás de dominio / HTTPS (activar con DEBUG=False)
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=True)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # HSTS solo si el dominio ya tiene HTTPS estable
    if env.bool('ENABLE_HSTS', default=False):
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    if env.bool('SECURE_SSL_REDIRECT', default=False):
        SECURE_SSL_REDIRECT = True


