# Generated by Django 5.0.14 on 2026-06-04 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagen de Categoría')),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='tienda.categoria', verbose_name='Categoría Padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código de Artículo (SKU)')),
                ('nombre', models.CharField(max_length=255, verbose_name='Descripción / Nombre')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('marca', models.CharField(default='Makita', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('tipo', models.CharField(choices=[('herramienta', 'Herramienta'), ('accesorio', 'Accesorio'), ('repuesto', 'Repuesto')], default='herramienta', max_length=20, verbose_name='Tipo de Producto')),
                ('familia_sap', models.CharField(help_text='Ej: REPUESTOS, ACCESORIOS, EQUIPOS', max_length=100, verbose_name='Familia SAP')),
                ('categoria_sap', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría SAP')),
                ('status_sap', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status SAP')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta (Lista General)')),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Costo')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=5, verbose_name='Stock Mínimo Alerta')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Principal')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('voltaje', models.CharField(blank=True, help_text='Ej: 18V LXT, 40V Max, 220V', max_length=50, null=True, verbose_name='Voltaje')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo / Visible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='tienda.categoria', verbose_name='Categoría Comercial')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
