# Generated by Django 5.0.14 on 2026-07-21 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255, verbose_name='Archivo')),
                ('tipo_archivo', models.CharField(choices=[('repuestos', 'Repuestos'), ('accesorios_equipos', 'Equipos y Accesorios'), ('auto', 'Detectado automáticamente')], default='auto', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('total_nuevos', models.PositiveIntegerField(default=0)),
                ('total_actualizados', models.PositiveIntegerField(default=0)),
                ('total_sin_cambio', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, default='')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_catalogo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación de catálogo',
                'verbose_name_plural': 'Importaciones de catálogo',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LogCambioImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.CharField(db_index=True, max_length=50)),
                ('tipo_cambio', models.CharField(choices=[('nuevo', 'Producto nuevo'), ('precio_sube', 'Precio subió'), ('precio_baja', 'Precio bajó'), ('nombre', 'Nombre cambió'), ('codigo', 'Código cambió'), ('reactivado', 'Reactivado')], max_length=20)),
                ('campo', models.CharField(blank=True, default='', max_length=50)),
                ('valor_anterior', models.TextField(blank=True, default='')),
                ('valor_nuevo', models.TextField(blank=True, default='')),
                ('detalle', models.CharField(blank=True, default='', max_length=255)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='tienda.importacioncatalogo')),
            ],
            options={
                'verbose_name': 'Log de cambio de importación',
                'verbose_name_plural': 'Logs de cambios de importación',
                'ordering': ['id'],
            },
        ),
    ]
