# Generated by Django 5.0.14 on 2026-07-21 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_sedes_reserva_validacion'),
        ('tienda', '0005_web_promo_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_sede', to='tienda.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='sistema.sede')),
            ],
            options={
                'verbose_name': 'Stock por sede',
                'verbose_name_plural': 'Stocks por sede',
                'unique_together': {('producto', 'sede')},
            },
        ),
    ]
