# Generated by Django 5.0.14 on 2026-07-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_sedes_reserva_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacioncatalogo',
            name='total_errores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logcambioimportacion',
            name='tipo_cambio',
            field=models.CharField(choices=[('nuevo', 'Producto nuevo'), ('precio_sube', 'Precio subió'), ('precio_baja', 'Precio bajó'), ('nombre', 'Nombre cambió'), ('codigo', 'Código cambió'), ('reactivado', 'Reactivado'), ('error', 'Error / fila omitida')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo de adquisición. No se importa del Excel de lista.', max_digits=12, verbose_name='Precio de compra / costo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_tachado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio anterior mostrado tachado (con IGV). Si se llena junto al precio web, se marca como promoción.', max_digits=12, null=True, verbose_name='Precio tachado (web)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, help_text='LISTA GENERAL del Excel Makita. El precio al público sugerido es lista × 1.18.', max_digits=12, verbose_name='Precio lista (sin IGV)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_web',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta en la tienda web (con IGV). Si está vacío se usa lista × 1.18.', max_digits=12, null=True, verbose_name='Precio final (web)'),
        ),
    ]
