# Generated by Django 5.0.14 on 2026-07-22 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_precios_igv_caja_movimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mostrar_ficha_tecnica',
            field=models.BooleanField(default=False, help_text='Si está activo, se muestra el recuadro de atributos nombre/valor en la ficha pública.', verbose_name='Mostrar ficha técnica en web'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_web',
            field=models.CharField(blank=True, default='', help_text='Si está vacío, en la tienda se muestra el nombre importado.', max_length=255, verbose_name='Nombre para la web'),
        ),
        migrations.CreateModel(
            name='ProductoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='tienda.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Atributo de ficha técnica',
                'verbose_name_plural': 'Atributos de ficha técnica',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/%Y/%m/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tienda.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
