# Generated by Django 5.0.14 on 2026-08-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_nombre_web_ficha_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='status_sap',
            field=models.CharField(blank=True, help_text='Color del Excel Makita (Verde, Amarillo, Rojo, Morado, Azul). Indica disponibilidad en Lima; es independiente del stock de tienda/web.', max_length=50, null=True, verbose_name='Color lista Makita'),
        ),
    ]
