# Generated by Django 5.0.14 on 2026-08-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_color_lista_lima_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcambioimportacion',
            name='detalle',
            field=models.TextField(blank=True, default='', verbose_name='Motivo / detalle'),
        ),
        migrations.AlterField(
            model_name='logcambioimportacion',
            name='tipo_cambio',
            field=models.CharField(choices=[('nuevo', 'Producto nuevo'), ('precio_sube', 'Precio subió'), ('precio_baja', 'Precio bajó'), ('nombre', 'Nombre cambió'), ('codigo', 'Código cambió'), ('status', 'Color lista (Status)'), ('familia', 'Familia SAP'), ('reactivado', 'Reactivado'), ('error', 'Error / fila omitida')], max_length=20),
        ),
    ]
