# Generated by Django 5.0.14 on 2026-08-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_log_importacion_detalle_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacioncatalogo',
            name='archivo',
            field=models.FileField(blank=True, help_text='Solo se conserva si la importación falla o tiene errores de fila. Tras un éxito sin errores se elimina del disco (los cambios quedan en el log).', null=True, upload_to='importaciones/%Y/%m/', verbose_name='Archivo guardado'),
        ),
    ]
