# Generated by Django 5.0.14 on 2026-08-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_importacioncatalogo_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoimagen',
            options={'ordering': ['-es_principal', 'orden', 'id'], 'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Imágenes de producto'},
        ),
        migrations.AddField(
            model_name='producto',
            name='posicion_despiece',
            field=models.CharField(blank=True, help_text='Número o código de posición en el diagrama de desarme interno (Ej. Pos. 42).', max_length=50, null=True, verbose_name='Posición en despiece'),
        ),
    ]
