# Generated by Django 5.0.14 on 2026-08-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_productoimagen_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('herramienta', 'Herramienta'), ('accesorio', 'Accesorio'), ('repuesto', 'Repuesto'), ('servicio', 'Servicio / Varios')], default='herramienta', max_length=20, verbose_name='Tipo de Producto'),
        ),
    ]
