# Generated by Django 5.0.14 on 2026-06-04 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Apertura')),
                ('monto_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de Cierre')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='TicketPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número de Serie')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IGV (18%)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('tipo_comprobante', models.CharField(choices=[('ticket', 'Ticket Simple'), ('boleta', 'Boleta de Venta'), ('factura', 'Factura')], default='ticket', max_length=20, verbose_name='Tipo de Comprobante')),
                ('ruc_cliente', models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('impreso', models.BooleanField(default=False, verbose_name='Impreso')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_pos', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Ticket POS',
                'verbose_name_plural': 'Tickets POS',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
