# Generated by Django 5.0.14 on 2026-07-21 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('sistema', '0002_sedes_reserva_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajasesion',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to='sistema.sede', verbose_name='Sede'),
        ),
    ]
