# Generated by Django 5.0.14 on 2026-09-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_movimientocaja_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta Crédito/Débito'), ('transferencia', 'Transferencia Bancaria')], default='efectivo', help_text='Solo el efectivo afecta el arqueo de gaveta.', max_length=20, verbose_name='Método de pago'),
        ),
    ]
