# Generated by Django 5.0.14 on 2026-06-04 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('pedidos', '0002_pedido_caja_sesion'),
        ('tienda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_alternativo', models.CharField(blank=True, help_text='Usar solo si el producto no existe en el catálogo.', max_length=150, null=True, verbose_name='Modelo Manual (No Catálogo)')),
                ('numero_serie', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Número de Serie')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('horas_uso_actuales', models.PositiveIntegerField(default=0, verbose_name='Horas de Uso Actuales')),
                ('horas_proximo_mantenimiento', models.PositiveIntegerField(default=300, verbose_name='Próximo Mantenimiento (Horas)')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_mantenimiento', 'En Mantenimiento'), ('dado_de_baja', 'Dado de Baja')], default='activo', max_length=20, verbose_name='Estado de Equipo')),
                ('garantia_hasta', models.DateField(blank=True, null=True, verbose_name='Garantía Vence El')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='clientes.cliente', verbose_name='Cliente')),
                ('pedido_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_registrados', to='pedidos.pedido', verbose_name='Pedido de Origen')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos_registrados', to='tienda.producto', verbose_name='Producto de Catálogo')),
            ],
            options={
                'verbose_name': 'Equipo Registrado',
                'verbose_name_plural': 'Equipos Registrados',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo_300h', 'Preventivo 300 Horas'), ('correctivo', 'Correctivo / Reparación'), ('garantia', 'Garantía Técnica')], default='preventivo_300h', max_length=25, verbose_name='Tipo de Mantenimiento')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Entrega Estimada')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Entrega Real')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico Inicial')),
                ('trabajos_realizados', models.TextField(blank=True, verbose_name='Trabajos Realizados')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Mano de Obra')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de Repuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Total')),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado (Recepción)'), ('en_proceso', 'En Proceso de Reparación'), ('listo', 'Listo para Retiro (Completado)'), ('entregado', 'Entregado al Cliente')], default='ingresado', max_length=20, verbose_name='Estado de Mantenimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='mantenimiento.equiporegistrado', verbose_name='Equipo')),
                ('repuestos_usados', models.ManyToManyField(blank=True, related_name='mantenimientos_usados', to='tienda.producto', verbose_name='Repuestos Usados')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado')),
            ],
            options={
                'verbose_name': 'Orden de Mantenimiento',
                'verbose_name_plural': 'Órdenes de Mantenimiento',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
