# Generated by Django 5.0.14 on 2026-08-03 14:35

import django.db.models.deletion
from django.db import migrations, models


def _backfill_ots(apps, schema_editor):
    Mantenimiento = apps.get_model('mantenimiento', 'Mantenimiento')
    ContadorOT = apps.get_model('mantenimiento', 'ContadorOT')
    n = 612
    for m in Mantenimiento.objects.order_by('id'):
        if not m.numero_ot:
            n += 1
            m.numero_ot = f'OT-{n}'
            m.save(update_fields=['numero_ot'])
    ContadorOT.objects.update_or_create(pk=1, defaults={'ultimo': n})


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo', models.PositiveIntegerField(default=612)),
            ],
            options={
                'verbose_name': 'Contador OT',
                'verbose_name_plural': 'Contador OT',
            },
        ),
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.AddField(
            model_name='equiporegistrado',
            name='boleta_factura',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Boleta / Factura'),
        ),
        migrations.AddField(
            model_name='equiporegistrado',
            name='distribuidor',
            field=models.CharField(blank=True, default='', help_text='Si no lo vendimos nosotros (otra tienda Makita).', max_length=255, verbose_name='Distribuidor / tienda de compra'),
        ),
        migrations.AddField(
            model_name='equiporegistrado',
            name='notas',
            field=models.TextField(blank=True, default='', verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='equiporegistrado',
            name='origen',
            field=models.CharField(choices=[('nuestro', 'Vendido por nosotros'), ('externo', 'Otra tienda / externo')], db_index=True, default='nuestro', max_length=20, verbose_name='Origen del equipo'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='accesorios',
            field=models.TextField(blank=True, default='', verbose_name='Accesorios recibidos'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='atencion_sr',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Att. Sr.'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='autorizacion_mpe',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Autorización MPE'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='boleta_factura',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Boleta / Factura'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='categoria_falla',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Categoría falla'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='causa',
            field=models.TextField(blank=True, default='', verbose_name='A causa de qué / informe falla'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='comentario_mpe',
            field=models.TextField(blank=True, default='', verbose_name='Comentario MPE'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='distribuidor',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Distribuidor'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_garantia',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado a Lima'), ('aprobado', 'Aprobado MPE'), ('rechazado', 'Rechazado MPE')], default='borrador', max_length=20, verbose_name='Estado garantía Lima'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_aprobacion_mpe',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha aprobación / revisión MPE'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de compra'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de recepción'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='informe_tecnico',
            field=models.TextField(blank=True, default='', verbose_name='Informe técnico y recomendaciones'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='mano_obra_mpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mano de obra MPE'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='nombre_mpe',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nombre MPE'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='numero_ot',
            field=models.CharField(blank=True, db_index=True, help_text='Correlativo con prefijo OT- (ej. OT-612).', max_length=20, null=True, unique=True, verbose_name='Nº OT'),
        ),
        migrations.RunPython(
            code=_backfill_ots,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='diagnostico',
            field=models.TextField(blank=True, default='', verbose_name='Diagnóstico / falla (síntoma)'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('preventivo_300h', 'Preventivo 300 Horas'), ('correctivo', 'Correctivo / Reparación'), ('garantia', 'Garantía Técnica')], default='correctivo', max_length=25, verbose_name='Tipo de Mantenimiento'),
        ),
        migrations.CreateModel(
            name='OrdenTrabajoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='mantenimiento.mantenimiento', verbose_name='OT')),
            ],
            options={
                'verbose_name': 'Línea de OT',
                'verbose_name_plural': 'Líneas de OT',
                'ordering': ['orden', 'id'],
            },
        ),
    ]


