# Generated by Django 5.0.14 on 2026-08-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_ot_historial_garantia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contadorot',
            options={'verbose_name': 'Configuración correlativo OT', 'verbose_name_plural': 'Configuración correlativo OT'},
        ),
        migrations.AlterField(
            model_name='contadorot',
            name='ultimo',
            field=models.PositiveIntegerField(default=0, help_text='Si el último papel fue 700, deja 700 aquí: la siguiente será OT-701.', verbose_name='Último número OT emitido'),
        ),
    ]
